### ISSUE TITLE
finding "APIs & Auth -> Push"

### ISSUE THREAD

**Issue by andrewroberts** [Spencer-Easton/Apps-Script-Gmail-Push-Notifications#1]
Hi Spencer,

"For this to work you must first publish your script as a draft to the chrome webstore. Then in the dev console add your scripts published webapp URL without the trailing '/exec' to APIs & Auth -> Push".

I've had a good dig around but I can't find the "APIs & Auth -> Push", could you give me a few pointers to finding this.

Thanks,

Andrew

**Comment by Spencer-Easton** [comment]
Hey Andrew,
  They moved this to credential screen. It will be one of the tabs on the top. Also there is a search bar on the top center of the page. Just search for `Domain verification` and it should get you there.
Made the change to Readme. 

Spence
